# Author: Mazhar Ahmed, CTO, Oceanize Inc
# All rights reserved. Copyright (c) Oceanize Inc
version: '3'
services:
  app:
    image: "andreamorim/flask-restful-architecture-mysql:latest"
    container_name: flask_app
    build:
      # build the image from Dockerfile
      context: .
      dockerfile: Dockerfile
    environment:
      # set database, memcached etc credentials
      DB_USER: root
      DB_PASS: flask
      # sometimes using localhost don't works then use the database name insted
      DB_HOST: mysql
      DB_NAME: preditivodb
    links:
      # network connection with these services
      - mysql
    depends_on:
      # build those images first
      - mysql
    labels:
      project: "flask"
      # day: "9 Sep 2019"
    restart: always
    ports:
      # bind on our 5000 port because most people have 80, 8080 already bound
      - "8000:5000"
    volumes:
      - .:/usr/app

  mysql:
    # let's grab from mysql 8.0 image
    image: mysql:8.0
    container_name: flask_mysql
    restart: unless-stopped
    labels:
      project: "flask"
      # day: "9 Sep 2019"
    environment:
      # credentials
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: flask
      MYSQL_USER: admin
      MYSQL_PASSWORD: flask
    ports:
      - "306:3306"
    volumes:
        # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql
  
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: flask_phpmyadmin
    restart: always
    labels:
      project: "flask"
      # day: "9 Sep 2019"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: flask
      # MYSQL_ROOT_PASSWORD: flask
    ports:
      - "8081:80"

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local